name: 'Repo Lockdown'

on:
  pull_request_target:
    types: opened

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v3
        with:
          exclude-pr-created-before: '2022-01-01T00:00:00Z'
          pr-comment: 'This project does not accept pull requests. Please use issues to report bugs or suggest new features.'
          process-only: 'prs'
